<!-- Left column/section -->
<section class="column width8 first">
    <div class="colgroup leading">
        <div class="column width6 first">
			<div id="descripton">
				<h2>Shorten, share and track your links.</h2></p>
			</div>
			
			<div id="shorty">
				<h5>Shorten Links Here:</h5>
				<textarea name="url" rows="3" cols="70" tabindex="1" id="urltext" ></textarea><br />
				<button id="shorten" class="btn">Shorten</button>
			</div>
			<div id="shortened"></div>
        </div>
    </div>

    <div class="clear">&nbsp;</div>
</section>
<!-- End of Left column/section -->
