<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>Shortener Url</title>
        <link href="<?=$this->cdn('styles')?>/favicon.ico" rel="shortcut icon" type="image/ico" />
        <link href="<?=$this->cdn('styles')?>/adm/administry.css" media="screen" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?=$this->cdn('scripts')?>/index.php?c=auto&amp;f=,hol/jquery/jquery-1.4.2.min.js,hol/zfurl.js" ></script>
        
        <!-- Internet Explorer Fixes -->
        <!--[if IE]>

        <link rel="stylesheet" type="text/css" media="all" href="<?=$this->cdn('styles')?>/ie.css"/>

        <script src="<?=$this->cdn('scripts')?>/hol/html5.js"></script>

        <![endif]-->
        <!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
        <!--[if lt IE 8]>

        <script src="<?=$this->cdn('scripts')?>/hol/IE8.js"></script>

        <![endif]-->


    </head>
    <body onload="zfurlinit();">

	<!-- Page content -->
	<div id="page">
		<!-- Wrapper -->
		<div class="wrapper">
                <?=$this->layout()->content;?>
		</div>
		<!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->

	<!-- Page footer -->
	<footer id="bottom">
            <div class="wrapper">
                <nav>
                    <a href="#">Dashboard</a> ·
                    <a href="#">Content</a> ·
                    <a href="#">Reports</a> ·
                    <a href="#">Users</a> ·
                    <a href="#">Media</a> ·
                    <a href="#">Events</a> ·
                    <a href="#">Newsletter</a> ·
                    <a href="#">Settings</a>
                </nav>
            </div>
	</footer>
	<!-- End of Page footer -->

    </body>
</html>