<h1>About</h1>
<p>
ZFurl is a URL shortening service built with the Zend Frame Work. ZFurl stands for Zend Framework Url. This is a demo project put
together by Tom Printy. The goal of this site was to demostrate the Zend Framework and to start for me to start using Ajax,
specificaly withe JQuery.  I would like to thank Wa-Jiw Casey for helping me with my Javascript AJAX requests and pointing out what
I was doing wrong and showing me some short cuts.
</p>
<p>
This code is hosted on Google Code and I would appreciate any comments or recommendations or improvements that you would like to
see.
</p>